name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mongodb-version: ['8.0']

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: lexoraDB
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.12.0
        with: 
          mongodb-version: ${{ matrix.mongodb-version }}

      - name: Setup JDK 21
        uses: actions/setup-java@v3.14.1
        with: 
          java-version: 21
          distribution: temurin

      # This creates the machine-readable format .class file inside a .jar container
      # Bcz with github actions there is no compiler do it automatically
      - name: Build the project
        working-directory: backend # Just like cd backend
        run: mvn clean package --no-transfer-progress 

      - name: Run Spring boot application
        working-directory: backend # Just like cd backend
        run: nohup java -jar target/*.jar & # Runs the whole command in the background
        # nohup stands for no hang up

      - name: waiting for springboot to start
        run: |
          echo "Waiting to springboot to become healthy"
          for i in {1..30}; do
            if curl -s http://localhost:8080/actuator/health | grep UP; then
              echo "Spring Boot is up!"
              break
            fi
            echo "Waiting..."
            sleep 5
          done
        # curl -s Sends an HTTP GET request silently. get a json like {"status":"UP"}
        # fi - End of the if statment. Not Else 

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.9.1
        with:
          node-version: '20'

      - name: Install frontend dependancies
        working-directory: ./Frontend
        run: npm ci --legacy-peer-deps # npm ci is faster than npm install

      - name: Build frontend
        working-directory: ./Frontend
        run: npm run build

      # Use http-server instead of serve (more compatible with Selenium tests)
      - name: Serve frontend
        working-directory: ./Frontend
        run: |
          npm install -g http-server
          nohup http-server ./dist -p 5173 &
        # nohup makes the process continue running in the background even after the command step ends

      - name: Wait for frontend to be ready
        run: |
          echo "Waiting for frontend to become ready..."
          for i in {1..30}; do
            status_code=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:5173/Lexora/)
            if [ "$status_code" -eq 200 ]; then
              echo "Frontend is ready!"
              break
            fi
            echo "Waiting..."
            sleep 5
          done

        # We hit the exact route /Lexora/ since Selenium tests also go there
        # If 'Lexora' text is found in the HTML, we assume it's ready

      - name: Install Chrome for Selenium
        run: |
          sudo apt update
          sudo apt install -y wget unzip xvfb libxi6 libgconf-2-4 libnss3 libxss1 libappindicator1 libindicator7
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome-stable_current_amd64.deb || sudo apt-get -f install -y
        # Installs Chrome browser so Selenium can control it
        # Also installs dependencies needed for Chrome to run in headless mode

      - name: Start virtual display for headless Chrome
        run: |
          export DISPLAY=:99
          Xvfb :99 -screen 0 1920x1080x24 > /dev/null 2>&1 &
        env:
          DISPLAY: :99
        # Xvfb is like a virtual monitor required by ChromeDriver
        # DISPLAY env variable makes Selenium connect to the virtual screen

      - name: Run JUnit tests
        working-directory: backend
        env:
          DISPLAY: :99 # Required so Selenium can run with Chrome in CI
        run: mvn test
        # Runs Selenium tests written in Java using JUnit
        # Will automatically open the browser and test the full workflow
