name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mongodb-version: ['8.0']

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: lexoraDB
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.12.0
        with: 
          mongodb-version: ${{ matrix.mongodb-version }}

      - name: Setup JDK 21
        uses: actions/setup-java@v3.14.1
        with: 
          java-version: 21
          distribution: temurin

      - name: Build the project
        working-directory: backend
        run: mvn clean package --no-transfer-progress 

      - name: Run Spring boot application
        working-directory: backend
        run: nohup java -jar target/*.jar &

      - name: Wait for Spring Boot to start
        run: |
          echo "Waiting for Spring Boot to become healthy"
          for i in {1..30}; do
            if curl -s http://localhost:8080/actuator/health | grep UP; then
              echo "Spring Boot is up!"
              break
            fi
            echo "Waiting..."
            sleep 5
          done

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.9.1
        with:
          node-version: '20'

      - name: Install frontend dependencies
        working-directory: ./Frontend
        run: npm ci --legacy-peer-deps

      - name: Build frontend
        working-directory: ./Frontend
        run: npm run build

      - name: Serve frontend
        working-directory: ./Frontend
        run: |
          npm install -g serve wait-on
          nohup serve -s dist -l 5173 --single &

      - name: Wait for frontend to be ready
        run: wait-on http://localhost:5173/Lexora/

      - name: Install Chrome **102** and ChromeDriver **102**
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip wget
          
          wget https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_102.0.5005.61-1_amd64.deb
          sudo dpkg -i google-chrome-stable_102.0.5005.61-1_amd64.deb || sudo apt-get -f install -y
          
          wget https://chromedriver.storage.googleapis.com/102.0.5005.61/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          chromedriver --version
          google-chrome --version

      - name: Run JUnit tests
        working-directory: backend
        run: mvn test

      - name: Print test failure report
        if: failure()  # Only runs if previous step failed
        run: |
          echo "Printing Surefire test logs:"
          cat backend/target/surefire-reports/*.txt || true

