name: Full CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # ----------------------
  # 1. JUnit Unit Tests
  # ----------------------
  junit-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        ports: [3306:3306]
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: lexoraDB
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=5

    strategy:
      matrix:
        mongodb-version: ['8.0']

    steps:
      - uses: actions/checkout@v4

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.12.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: temurin

      - name: Build backend
        working-directory: backend
        run: mvn clean package --no-transfer-progress

      - name: Run unit & service tests (skip Selenium)
        working-directory: backend
        run: mvn test -Dtest=!com.NoIdea.Lexora.Selenium.**

  # ----------------------
  # 2. Frontend Build & Lint
  # ----------------------
  frontend-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm install

      - name: Run linter
        working-directory: frontend
        run: npm run lint

      - name: Build frontend
        working-directory: frontend
        run: npm run build

  # ----------------------
  # 3. Selenium E2E Tests
  # ----------------------
  selenium-e2e:
    runs-on: ubuntu-latest
    needs: [junit-tests, frontend-check]

    services:
      mysql:
        image: mysql:8.0
        ports: [3306:3306]
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: lexoraDB
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=5

    strategy:
      matrix:
        mongodb-version: ['8.0']

    steps:
      - uses: actions/checkout@v4

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.12.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: temurin

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install frontend and start dev server
        working-directory: frontend
        run: |
          npm install
          nohup npm run dev &  # Assumes frontend on http://localhost:5173
          sleep 10

      - name: Run Selenium E2E tests
        working-directory: backend
        run: mvn test -Dtest=com.NoIdea.Lexora.Selenium.**

  # ----------------------
  # 4. (Optional) Deploy Step
  # ----------------------
  deploy:
    runs-on: ubuntu-latest
    needs: [junit-tests, frontend-check, selenium-e2e]

    steps:
      - name: Placeholder for deployment
        run: echo "Deploying app (implement this step)..."
