name: CI Pipeline - JUnit Only

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  junit-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mongodb-version: ['8.0']

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: lexoraDB
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.12.0
        with: 
          mongodb-version: ${{ matrix.mongodb-version }}

      - name: Setup JDK 21
        uses: actions/setup-java@v3.14.1
        with: 
          java-version: 21
          distribution: temurin

      - name: Build the project
        working-directory: backend
        run: mvn clean package --no-transfer-progress 

      - name: Run only JUnit tests
        working-directory: backend
        run: mvn test -Dtest=!com.NoIdea.Lexora.Selenium.**

      - name: Print test failure report
        if: failure()
        run: |
          echo "Printing Surefire test logs:"
          cat backend/target/surefire-reports/*.txt || true
