name: CICD Pipeline
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  frontend-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.9.1
        with:
          node-version: '20'
      
      - name: Install frontend dependencies
        working-directory: ./Frontend
        run: npm ci --legacy-peer-deps
      
      - name: Build frontend
        working-directory: ./Frontend
        run: npm run build
      
      - name: Upload frontend artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: Frontend/dist/
          retention-days: 1
          
  backend-build:
    needs: [frontend-build]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mongodb-version: ['8.0']
    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: lexoraDB
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.12.0
        with: 
          mongodb-version: ${{ matrix.mongodb-version }}
      
      - name: Setup JDK 21
        uses: actions/setup-java@v3.14.1
        with: 
          java-version: 21
          distribution: temurin
      
      - name: Build the project
        working-directory: backend
        run: mvn clean package -DskipTests --no-transfer-progress 
      
      - name: Upload full Maven target folder
        uses: actions/upload-artifact@v4
        with:
          name: backend-build-artifact
          path: backend/target/
          retention-days: 1

  unit-tests:
    runs-on: ubuntu-latest
    needs: [backend-build]
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
  
      - name: Setup JDK 21
        uses: actions/setup-java@v3.14.1
        with: 
          java-version: 21
          distribution: temurin
  
      - name: Download backend artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-build-artifact
          path: backend/target/   # Make sure this doesn't overwrite the project root
  
      - name: Run JUnit tests excluding Selenium
        working-directory: backend
        run: mvn test -Dtest=!Selenium*
        
      - name: Print test failure report
        if: failure()
        run: |
          echo "Printing Surefire test logs:"
          cat backend/target/surefire-reports/*.txt || true
      
      - name: Verify both services are running
        run: |
          echo "=== Backend Health Check ==="
          curl -s http://localhost:8080/actuator/health || echo "Backend health check failed"
          
          echo "=== Frontend Health Check ==="
          curl -s http://localhost:5173/Lexora/ || echo "Frontend health check failed"
          
          echo "=== Both services are ready for testing ==="
