name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v3.14.1
        with: 
          java-version: 21

      # This creates the machine-readable format .class file inside a .jar container
      # Bcz with github actions there is no compiler do it automatically
      - name: Build the project
        run: mvn clean package --no-transfer-progress 

      - name: Run Spring boot application
        run: java -jar target/*.jar

      
